### ISSUE TITLE
Chess.com game stops when loading a second window on same game

### ISSUE THREAD

**Issue by arthur-parmentier** [mdrokz/chessEngine#2]
Chess.com is preventing the loading of a second window, it completely stops the game... so the trick does not work anymore

**Comment by mdrokz** [comment]
> Chess.com is preventing the loading of a second window, it completely stops the game... so the trick does not work anymore

I see i will test the issue on my side and reply back to you

**Comment by mdrokz** [comment]
> Chess.com is preventing the loading of a second window, it completely stops the game... so the trick does not work anymore

i have a played a unrated game and tested my engine, i am not able to reproduce your issue it works fine for me on linux, can you explain in detail what is happening? or send me a video or screenshots

![image](https://user-images.githubusercontent.com/33598169/99193184-4e2f3f00-279d-11eb-9440-15102a9bd268.png)

see the chromium window is open

and you are using a dummy account right ? it only works if you have a seperate dummy account that can spectate your game

**Comment by arthur-parmentier** [comment]
Oups that is my mistake. I did not use a dummy account but the same one. I'll let you know in a minute if that was indeed the problem

**Comment by mdrokz** [comment]
> Oups that is my mistake. I did not use a dummy account but the same one. I'll let you know in a minute if that was indeed the problem

Sure
